<a href="https://colab.research.google.com/github/MohammadRahil001/Data_Analysis/blob/main/Adding_Removing__dimentions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CONCATENATING,FLATTENING AND ADDING DIMENSIONS

In [91]:
#flatten()
import numpy as np
arr = np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
 [[11,12,13],
  [14,15,16],
  [17,18,19]],
[[21,22,23],
 [24,25,26],
 [27,28,29]]])#3-d array
print(arr)
print("dimention:",np.ndim(arr))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
dimention: 3


changing array in one dimention

In [92]:
#Method 1 : flatten()
arr_flatten = arr.flatten()#change dimention of arr
print(arr_flatten)
print("dimention:",np.ndim(arr_flatten))#dimention 1

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26
 27 28 29]
dimention: 1


In [93]:
#Method2 : ravel
arr_ravel = arr.ravel()
print("array:",arr_ravel)

array: [ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26
 27 28 29]


In [94]:
#reshape
arr_reshape= np.reshape(arr,(27))#reshape into 0-d array
print("array:",arr_reshape)
print("shape:",arr_reshape.shape)
print("dimention:",np.ndim(arr_reshape)) # 1-d array

array: [ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26
 27 28 29]
shape: (27,)
dimention: 1


CONCATENATING ARRAYS

In [95]:
#adding 1-d array
arr2 = np.arange(10)
arr3 = np.arange(10)
print("array:",arr2,"\narray:",arr3)
arr4 = np.concatenate((arr2,arr3))
print("concate array:",arr4)
print("dimention:",np.ndim(arr4))

array: [0 1 2 3 4 5 6 7 8 9] 
array: [0 1 2 3 4 5 6 7 8 9]
concate array: [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
dimention: 1


In [101]:
# concatinate 2-d array
a = np.array([[1,2,3],[4,5,6]])
b= np.array([[7,8,9],[10,11,12]])
c = np.concatenate((a,b))# by default row wise axis = 0
print("array:",a)
print("array:",b)
print("concate array:",c)
print("shape:",a.shape,b.shape,c.shape)

c = np.concatenate((a,b),axis=1)#column wise
print("concate array:",c)
print("shape:",a.shape,b.shape,c.shape)
print("dim:",np.ndim(c))

array: [[1 2 3]
 [4 5 6]]
array: [[ 7  8  9]
 [10 11 12]]
concate array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (2, 3) (2, 3) (4, 3)
concate array: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
shape: (2, 3) (2, 3) (2, 6)
dim: 2


In [102]:
#concatinate 3-d array
arr5= np.arange(24)
arr5 = arr5.reshape(3,2,4)
print("array:",arr5)
arr6 = np.arange(100,124)
arr6 = arr6.reshape(3,2,4)
print("\narray:",arr6)

arr7 = np.concatenate((arr5,arr6))
print("\nconcate array:",arr7)
print(f"arr5 shape :{arr5.shape} arr6 shape :{arr6.shape} arr7 shape :{arr7.shape}")

arr7 = np.concatenate((arr5,arr6),axis=1)
print("\nconcate array:",arr7)
print(f"arr5 shape :{arr5.shape} arr6 shape :{arr6.shape} arr7 shape :{arr7.shape}")
print(np.ndim(arr7))

arr7 = np.concatenate((arr5,arr6),axis=2)
print("\nconcate array:",arr7)
print(f"arr5 shape :{arr5.shape} arr6 shape :{arr6.shape} arr7 shape :{arr7.shape}")

array: [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

array: [[[100 101 102 103]
  [104 105 106 107]]

 [[108 109 110 111]
  [112 113 114 115]]

 [[116 117 118 119]
  [120 121 122 123]]]

concate array: [[[  0   1   2   3]
  [  4   5   6   7]]

 [[  8   9  10  11]
  [ 12  13  14  15]]

 [[ 16  17  18  19]
  [ 20  21  22  23]]

 [[100 101 102 103]
  [104 105 106 107]]

 [[108 109 110 111]
  [112 113 114 115]]

 [[116 117 118 119]
  [120 121 122 123]]]
arr5 shape :(3, 2, 4) arr6 shape :(3, 2, 4) arr7 shape :(6, 2, 4)

concate array: [[[  0   1   2   3]
  [  4   5   6   7]
  [100 101 102 103]
  [104 105 106 107]]

 [[  8   9  10  11]
  [ 12  13  14  15]
  [108 109 110 111]
  [112 113 114 115]]

 [[ 16  17  18  19]
  [ 20  21  22  23]
  [116 117 118 119]
  [120 121 122 123]]]
arr5 shape :(3, 2, 4) arr6 shape :(3, 2, 4) arr7 shape :(3, 4, 4)
3

concate array: [[[  0   1   2   3 100 101 102 103]
  [  4   5   6   7 104 105 106 107]]

 [[

ADDING NEW DIMENSIONS

In [103]:
arr8= np.arange(10)
print("arrray:",arr8)
print("dim:",np.ndim(arr8))

arr9 = arr8[np.newaxis, :]
print("\narray:",arr9)
print("dim:",np.ndim(arr9))

arr9 = arr8[: , np.newaxis]
print("\narray:",arr9)
print("dim:",np.ndim(arr9))

arrray: [0 1 2 3 4 5 6 7 8 9]
dim: 1

array: [[0 1 2 3 4 5 6 7 8 9]]
dim: 2

array: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
dim: 2


In [105]:
#Vector Stacking Method
A = np.array([3, 4, 5])
B = np.array([1,9,0])
print("array:",A)
print("array:",B)
print("dim:",np.ndim(A),"dim:",np.ndim(B))
C = np.row_stack((A, B))
D = np.column_stack((A, B))

print("\nconcate array",C)
print("\nconacate array",D)
print("dim:",np.ndim(C),"dim:",np.ndim(D))

array: [3 4 5]
array: [1 9 0]
dim: 1 dim: 1

concate array [[3 4 5]
 [1 9 0]]

conacate array [[3 1]
 [4 9]
 [5 0]]
dim: 2 dim: 2


/tmp/ipython-input-1540747693.py:7: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  C = np.row_stack((A, B))


In [106]:
#column satck and row stack for conacate array
arr = np.arange(9)
arr = arr.reshape(3,3)
print("array:",arr)
arr1= np.column_stack((arr,arr,arr))# column wise repeate
arr2= np.row_stack((arr,arr))
print("array:",arr1)
print("array:",arr2)

array: [[0 1 2]
 [3 4 5]
 [6 7 8]]
array: [[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [6 7 8 6 7 8 6 7 8]]
array: [[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


/tmp/ipython-input-4030627308.py:6: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr2= np.row_stack((arr,arr))


In [107]:
arr3 = np.column_stack((arr[0],arr[0])) # adding 0 index of array [0,1,2] as coulmn stack 2 times
print("array:",arr3)

arr4 = np.column_stack((arr[0],arr[1],arr[2]))# creating arr with 0 ,1, 2 index element of arr with column stack
print("array:",arr4)

arr6 = np.column_stack((arr[1],arr[0]))
print("array:",arr6)

arr7= np.column_stack((arr[1],arr))
print("array:",arr7)

#dstack() function
arr8 = np.dstack((arr,arr))# dimention must match
print("array:",arr8)
arr9 = np.dstack((arr,arr,arr,arr))
print("array:",arr9, "dim:",np.ndim(arr9))

array: [[0 0]
 [1 1]
 [2 2]]
array: [[0 3 6]
 [1 4 7]
 [2 5 8]]
array: [[3 0]
 [4 1]
 [5 2]]
array: [[3 0 1 2]
 [4 3 4 5]
 [5 6 7 8]]
array: [[[0 0]
  [1 1]
  [2 2]]

 [[3 3]
  [4 4]
  [5 5]]

 [[6 6]
  [7 7]
  [8 8]]]
array: [[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]
  [5 5 5 5]]

 [[6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]] dim: 3


Repeating pattern of array

In [119]:
#tile() function : repeate same element across row and col
arr = np.array([[1,2],[3,4]])
print("array:",arr)
print("dimention:",np.ndim(arr))

repeat_arr = np.tile(arr,3)#reapeat accros col
print("array:\n",repeat_arr)

print("row wise array:",np.row_stack((arr,arr,arr)))#using row_satck for rowwise repetetion

repeat_arr = np.tile(arr,(2,4))#row=2 col=3
print("array:\n",repeat_arr)


array: [[1 2]
 [3 4]]
dimention: 2
array:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]]
row wise array: [[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]
array:
 [[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


/tmp/ipython-input-3788949036.py:9: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print("row wise array:",np.row_stack((arr,arr,arr)))#using row_satck for rowwise repetetion
