<a href="https://colab.research.google.com/github/MohammadRahil001/Data_Analysis/blob/main/Data_type_using_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,"a",1.1])
arr

array(['1', 'a', '1.1'], dtype='<U32')

In [4]:
i16 = np.dtype(np.int16)#creating a datatype of 64 int
print(i16)#int16

print(np.int64)#class of numpy

int16
<class 'numpy.int64'>


In [7]:
lst = [ [3.4, 8.7, 9.9],
[1.1, -7.8, -0.7],
[4.1, 12.3, 4.8] ]


print(type(lst))

arr = np.array(lst)
print(arr,np.dtype)

i64 = np.dtype(np.int64)
arr = np.array(lst, dtype=i64)
print(arr.dtype)# change the data type

<class 'list'>
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]] <class 'numpy.dtype'>
int64


In [9]:
dt = np.dtype([('density', np.int32)])
x = np.array([(393,), (337,), (256,)],dtype=dt)
print(x)
print(repr(x))#intenal representation i4 - i for integer 4 - 4 bytes

[(393,) (337,) (256,)]
array([(393,), (337,), (256,)], dtype=[('density', '<i4')])


In [ ]:
# little-endian ordering
dt = np.dtype('<d')
print(dt.name, dt.byteorder, dt.itemsize)
# big-endian ordering
dt = np.dtype('>d')
print(dt.name, dt.byteorder, dt.itemsize)
# native byte ordering
dt = np.dtype('d')
print(dt.name, dt.byteorder, dt.itemsize)

**STRUCTURED ARRAYS**

In [12]:
dt = np.dtype([('country', 'S20'), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
population_table = np.array([
('Netherlands', 393, 41526, 16928800),
('Belgium', 337, 30510, 11007020),
('United Kingdom', 256, 243610, 62262000),
('Germany', 233, 357021, 81799600),
('Liechtenstein', 205, 160, 32842),
('Italy', 192, 301230, 59715625),
('Switzerland', 177, 41290, 7301994),
('Luxembourg', 173, 2586, 512000),
('France', 111, 547030, 63601002),
('Austria', 97, 83858, 8169929),
('Greece', 81, 131940, 11606813)],dtype=dt)
print(population_table,population_table.dtype)
print(population_table['density'])

[(b'Netherlands', 393,  41526, 16928800)
 (b'Belgium', 337,  30510, 11007020)
 (b'United Kingdom', 256, 243610, 62262000)
 (b'Germany', 233, 357021, 81799600)
 (b'Liechtenstein', 205,    160,    32842)
 (b'Italy', 192, 301230, 59715625) (b'Switzerland', 177,  41290,  7301994)
 (b'Luxembourg', 173,   2586,   512000) (b'France', 111, 547030, 63601002)
 (b'Austria',  97,  83858,  8169929) (b'Greece',  81, 131940, 11606813)] [('country', 'S20'), ('density', '<i4'), ('area', '<i4'), ('population', '<i4')]


**UNICODE STRINGS IN ARRAY**

In [24]:
dt = np.dtype([('country', np.str_, 20),('density', 'i4'),('area', 'i4'),('population', 'i4')])

print(population_table, population_table.dtype)

[('Netherlands', 393,  41526, 16928800) ('Belgium', 337,  30510, 11007020)
 ('United Kingdom', 256, 243610, 62262000)
 ('Germany', 233, 357021, 81799600)
 ('Liechtenstein', 205,    160,    32842)] [('country', '<U20'), ('density', '<i4'), ('area', '<i4'), ('population', '<i4')]


In [28]:
#saving previous data into a file
np.savetxt("population_table.csv",population_table,fmt="%s;%d;%d;%d",delimiter=";")

In [29]:
#reading file that priviously we save
x = np.genfromtxt("population_table.csv",
dtype=dt,
delimiter=";")
x


array([('Netherlands', 393,  41526, 16928800),
       ('Belgium', 337,  30510, 11007020),
       ('United Kingdom', 256, 243610, 62262000),
       ('Germany', 233, 357021, 81799600),
       ('Liechtenstein', 205,    160,    32842)],
      dtype=[('country', '<U20'), ('density', '<i4'), ('area', '<i4'), ('population', '<i4')])