<a href="https://colab.research.google.com/github/MohammadRahil001/Data_Analysis/blob/main/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create an arbitrary one dimensional array called "v"

In [77]:
import numpy as np
v = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Array is {v} \n Dimention of array is : {v.ndim}")
v = np.arange(1,11)
print(f"Array is {v} \n Dimention of array is : {v.ndim}")


Array is [ 1  2  3  4  5  6  7  8  9 10] 
 Dimention of array is : 1
Array is [ 1  2  3  4  5  6  7  8  9 10] 
 Dimention of array is : 1


2) Create a new array which consists of the odd indices of previously created array "v"

In [78]:
v1 = v[1::2] # 1 --> first element : ""--> last element: 2 steps to leave next nuber of elements
print(v1)# even indices elements

v2 = v[0::2]
print(v2)# odd indicis elements

[ 2  4  6  8 10]
[1 3 5 7 9]


3) Create a new array in backwards ordering from v.


In [79]:
v3 = v[::-1]# reverse order
print(v3)

[10  9  8  7  6  5  4  3  2  1]


What will be the output of the following code:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

In [80]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200#also change in original array.
print("result : " ,a[1])

result :  200


5) Create a two dimensional array called "m"

In [81]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(np.ndim(m))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


6) Create a new array from m, in which the elements of each row are in reverse order

In [82]:
m1 = m[:,::-1]
print("result\n",m1)

result
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


7) Another one, where the colunms are in reverse order

In [83]:
m2 = m[::-1]
print("result\n",m2)

result
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


8) Create an array from m, where columns and rows are in reverse order.

In [84]:
m3 =m[::-1,::-1]
print("result: \n",m3)

result: 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


9) Cut of the first and last row and the first and last column

In [85]:
#method 1
m4 = m[::2,::2]
print(m4)

#method 2
m5 = m[0::2,0::2]
print(m5)

m7 = m[1:-1,1:-1]
print("d",m7)
#method3
m8 = np.arange(1,16).reshape(5,3)# universal work on any order of matrix
a,b = np.shape(m)
m6 = m8[::a-1,::b-1]
print(m6)

[[1 3]
 [7 9]]
[[1 3]
 [7 9]]
d [[5]]
[[ 1  3]
 [ 7  9]
 [13 15]]
