<a href="https://colab.research.google.com/github/MohammadRahil001/Data_Analysis/blob/main/Random_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Random Number

In [ ]:
#Genrating a random number
import random
random_number = random.random()# give a number b/w 0 to 1
print(random_number)#it use seed to produce random number


0.05315895288944861


In [ ]:
#SystomRandom() : Generate random number with secure method (OS level)
from random import SystemRandom
system_random = SystemRandom()#It uses sources which are provided by the operating system.
print(system_random.random())


0.4349656438485333


In [ ]:
#generate a list of random numbers
random_lst = [random.random() for i in range(10)]#using random function
print(random_lst)


[0.06936878882600706, 0.8405155071697564, 0.3906831378625104, 0.348151329320018, 0.39982489537096466, 0.6801171204702858, 0.4547029556736193, 0.061550879139820935, 0.6823453230413897, 0.04241797182144269]


In [ ]:
#generate  list with systemrandom
systemrandom_lsst = [SystemRandom().random() for  i in range(10)]
print(systemrandom_lsst)

[0.6334060634943823, 0.4344153048249202, 0.659652042410943, 0.3817657531572427, 0.1076570913784517, 0.4724767887550524, 0.6792834217628958, 0.9079356526954789, 0.2668327101003585, 0.5199029133200405]


In [ ]:
#creating a function to generate random numbers
from random import SystemRandom, random
def random_generate(n,secure):
  lst = []
  if secure ==True:
    random_number = SystemRandom().random()
  else:
    random_number = random()
  for i in range(n):
    lst.append(random_number)
  return lst
print("secure: ",random_generate(10,True))
print("unsecure: ",random_generate(10,False))



secure:  [0.9317344750621578, 0.9317344750621578, 0.9317344750621578, 0.9317344750621578, 0.9317344750621578, 0.9317344750621578, 0.9317344750621578, 0.9317344750621578, 0.9317344750621578, 0.9317344750621578]
unsecure:  [0.5744799318826147, 0.5744799318826147, 0.5744799318826147, 0.5744799318826147, 0.5744799318826147, 0.5744799318826147, 0.5744799318826147, 0.5744799318826147, 0.5744799318826147, 0.5744799318826147]


check time takes for both functions

In [ ]:
%%timeit
random_generate(100,True)#SystomRandom function : slowest but highly secure


4.59 µs ± 81.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%%timeit
random_generate(100,False)#random function : average

4.39 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#Numpy for random numbers
import numpy as np
random_lst2 = [np.random.random() for i in range(10)]
print(random_lst2)

[0.9436615041507478, 0.0920275138796619, 0.12349577819561353, 0.5202951115504605, 0.7234234702610197, 0.12432795460825663, 0.8320245922017807, 0.7353981878604272, 0.2843085503518523, 0.2864578788062193]


In [ ]:
#time taken for numpy random method
%%timeit
np.random.random(100)#Faster


1.92 µs ± 58.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


RANDOM NUMBERS SATISFYING SUM-TO-ONE CONDITION

RANDOM INTEGER NUMBER

In [ ]:
list_random = np.random.random(100)
sum_of_list = list_random.sum()
print(sum_of_list)

normal_value = list_random/sum_of_list
print(normal_value.sum())#noramlized value

51.35252502705457
1.0


In [ ]:
#randint() : generate an integer with a specific range
random_integer = np.random.randint(1,10)
print("random integer: ",random_integer)

# genrating a list of random integers
random_int_lst = [np.random.randint(1,20) for i in range(10)]
print("list of random integers: ",random_int_lst)

random integer:  5
list of random integers:  [11, 18, 16, 16, 13, 17, 18, 8, 16, 4]


In [ ]:
#roll a die 10 times
from random import randint# using random.randint method
die_outcomes = [randint(1,7) for i in range(10)]
print("outcomes:",die_outcomes)
print(type(die_outcomes)) # list
#using np.random.randint() method

die_outcomes2 = np.random.randint(1,7,10) # (start,end,size)
print("outcomes:",die_outcomes2)
print(type(die_outcomes2))# numpy array
print("dim: ",die_outcomes2.ndim)


outcomes: [5, 5, 1, 6, 1, 1, 7, 2, 1, 2]
<class 'list'>
outcomes: [1 3 5 3 4 6 4 5 1 2]
<class 'numpy.ndarray'>
dim:  1


In [ ]:
#creating n-D array with random numbers
arr = np.random.randint(1,100,(3,3))
print("array:\n",arr)
print("dim: ",arr.ndim)#2 d array

arr2 = np.random.randint(50,60,(2,2,2))
print("array:\n",arr2)
print("dim: ",arr2.ndim)#3 d array

array:
 [[26 61 26]
 [13 51 89]
 [88 78 41]]
dim:  2
array:
 [[[53 52]
  [52 54]]

 [[51 52]
  [54 52]]]
dim:  3


Random Choice method

In [ ]:
#choice function : choose one element form list
from random import choice
lst =[1,2,3,4,5,6]
print(choice(lst))
print(choice(lst))

3
1


In [ ]:
#choice function on string list
string_lst = ["a","b","c","d","e"]
print(choice(string_lst))
print(choice(string_lst))

c
b


np.random.choice give some further possibilites

In [ ]:
from numpy.random import choice
lst = [1,2,3,4,5,6]
print(choice(lst))

lst2 = ["a","b","c","d","e"]
print(choice(lst2,2))#choose 2 values

3
['e' 'a']


In [ ]:
#choice function to create 2D array...
arr = np.random.randint(1,20,10)#1D array of 10 elements
print(arr)
print(choice(arr,size=(2,3)))#give 2D array

[19  2  9  7  8 19 12  9 13  4]
[[ 2  7 19]
 [ 2  4  7]]


In [ ]:
arr = np.random.randint(0,27,(3,3,3))
print(arr)
print(choice(arr.flatten(), size=(2,3)))

[[[17 14  1]
  [ 9 26 24]
  [12 25 20]]

 [[25 11 22]
  [ 0 25 26]
  [ 5 14 19]]

 [[26 26 23]
  [15 25  0]
  [ 7  0 26]]]
[[26 26 11]
 [20  7 25]]


Password generator using numpy choice function

In [ ]:
#password generator using random module
from random import choice
def password_generator(length):
  charectors = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#"
  password = ""
  for i in range(length):
    password += choice(charectors)
  return password
print(password_generator(10))

OsfXD9GxZg


Random Sample function

In [ ]:
from numpy.random import random_sample
#np.random.random_sample use to create a large array with random numbers...
sample = random_sample(10)
print(sample)

sample2 = random_sample((2,3))# 2D array
print(sample2,type(sample2))

import random
sample3 = random.sample(range(1,60),10)
print(sample3,type(sample3))

[0.37253135 0.13698153 0.74410595 0.83699728 0.4109399  0.56731825
 0.13911318 0.30130105 0.16939535 0.2676143 ]
[[0.08692824 0.81506226 0.15757272]
 [0.0555223  0.45085607 0.10809386]] <class 'numpy.ndarray'>
[22, 32, 18, 23, 39, 28, 45, 34, 6, 47] <class 'list'>


**True Random Number** : The truth is that most random numbers used in computer
programs are pseudo-random. The numbers are generated in a predictable way, because the algorithm is
deterministic. Pseudo-random numbers are good enough for many purposes, but it may not be "true" random
rolling dice or lottery drawings.

In [ ]:
import random
for i in range(10):
  random.seed(1)
  print(random.randint(1,10),"  ",end="")# give always same number it always depend on seed
  random.seed(2)
print(random.randint(1,10))# same seed same number : we can manupulate seed and ged=t same number some it is not secure for real life problems...

3   1
3   1
3   1
3   1
3   1
3   1
3   1
3   1
3   1
3   1


**Creating a guess the number game**

In [ ]:
from random import randint
comp = randint(1,10)
user = int(input("guess the number(1-10): "))
if user == comp:
  print("correct")
else:
  print(f"wrong correct number is {comp}")

guess the number(1-10): 10
correct


**Creating a Rock Papper Scissor game...**

In [ ]:
from random import choice

choices = ["Rock", "Papper", "Scissor"]
while(True):
  bot = choice(choices)
  user = int(input("0. Exit \n1. Rock\n2. Papper\n3. Scissor\nEnter: "))
  if user == 0:
    break
  elif user == 1:
    user = "Rock"
  elif user == 2:
    user = "Papper"
  elif user == 3:
    user = "Scissor"
  else:
    print("Invalid input")
    continue

  print(f"bot choice: {bot}")
  print(f"user choice: {user}")

  if user == bot:
    print("Draw..")
  elif user == "Rock" and bot == "Scissor" or user == "Scissor" and bot == "Papper" or  user == "Papper" and bot == "Rock":
    print("User win")
  else:
    print("Bot win")




0. Exit 
1. Rock
2. Papper
3. Scissor
Enter: 1
bot choice: Scissor
user choice: Rock
User win
0. Exit 
1. Rock
2. Papper
3. Scissor
Enter: 2
bot choice: Scissor
user choice: Papper
Bot win
0. Exit 
1. Rock
2. Papper
3. Scissor
Enter: 1
bot choice: Papper
user choice: Rock
Bot win
0. Exit 
1. Rock
2. Papper
3. Scissor
Enter: 0
